<?php

namespace App\Http\Sections;

use AdminColumn;
use AdminDisplay;
use AdminForm;
use AdminFormElement;


use App\GeneralData;

use Illuminate\Database\Eloquent\Model;
use SleepingOwl\Admin\Contracts\Form\FormInterface;
use SleepingOwl\Admin\Contracts\Display\DisplayInterface;

use SleepingOwl\Admin\Form\Buttons\FormButton;
use SleepingOwl\Admin\Form\Buttons\SaveAndClose;
use SleepingOwl\Admin\Section;
use SleepingOwl\Admin\Contracts\Initializable;


class GeneralDatas extends Section implements Initializable
{

    /**
     * Class Posts
     *
     * @property \App\Model $model
     *
     * @see http://sleepingowladmin.ru/docs/model_configuration_section
     */
    protected $checkAccess = false;

    /**
     * @var string
     */
    protected $title = 'Общие данные';

    /**
     * @var string
     */
    protected $alias = 'general-data';

    /**
     * Initialize class.
     */
    public function initialize()
    {
        $this->addToNavigation()->setIcon('fa fa-globe');
    }


    /**
     * @return DisplayInterface
     */
    public function onDisplay()
    {

        foreach (GeneralData::limit(1)->pluck('id') as $id){
            if (! is_null($id)){

                $oneForm[] = $this->fireEdit($id);
            }
        }
        return $oneForm[0];
    }

    /**
     * @param int $id
     *
     * @return FormInterface
     */
    public function onEdit($id){

        $cancel =new FormButton();
        $cancel->setUrl(redirect()->back()->getTargetUrl())
            ->setText(trans('sleeping_owl::lang.table.cancel'));
        $buttons = [
            'save' => (new SaveAndClose())->setText(trans('sleeping_owl::lang.table.save')),
            'cancel' => $cancel
        ];

        $form = AdminForm::panel()->addBody([
            AdminFormElement::textarea('banner', 'Баннер')->required(),
            AdminFormElement::text('email', 'Почта')->required(),
            AdminFormElement::text('tel_numb', 'Номер телефона')->required(),
            AdminFormElement::text('tel_text', 'Текст телефона')->required(),
            AdminFormElement::text('address', 'Адрес')->required(),
        ]);

        $form->getButtons()->setButtons($buttons);

        return $form;
    }




    public function isDeletable(Model $model)
    {
        return parent::isDeletable($model); // TODO: Change the autogenerated stub
    }
}
